# Generated by Django 4.2.1 on 2023-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_messagelikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
