# Generated by Django 4.2.1 on 2023-06-13 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_messages_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelikes',
            name='liker',
        ),
        migrations.AddField(
            model_name='messagelikes',
            name='likes',
            field=models.ManyToManyField(related_name='messagelike', to=settings.AUTH_USER_MODEL),
        ),
    ]
