# Generated by Django 4.2.1 on 2023-06-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_messagelikes_liker_messagelikes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelikes',
            name='likes',
        ),
        migrations.AddField(
            model_name='messagelikes',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
