# Generated by Django 4.2.1 on 2023-06-13 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_messagelikes_likes_messagelikes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelikes',
            name='liker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagelikes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
