# Generated by Django 4.2.1 on 2023-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_messagelikes_liker_alter_messagelikes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelikes',
            name='likes',
        ),
    ]
